package constants

var (
	SERVER_NAME = "SERVER_NAME"
	USER_NAME   = "USER_NAME"
	PASSWORD    = "PASSWORD"
	DATABASE    = "DATABASE"
	SECRET_KEY  = "SECRET_KEY"
	SUCCESS     = "SUCCESS"
	ERROR       = "ERROR"
)
